export const globalMap = new Map()
globalMap.set('numberOfMessagesToday', '今日消息量')
globalMap.set('numberOfPlatformFiles', '平台文件数')
globalMap.set('accumulatedTemplateOwnership', '累计模板数')
globalMap.set('numberOfApps', '渠道 APP 数')
globalMap.set('chartsMessageOption', '消息详情')
globalMap.set('chartsTemplateOption', '模板使用 TOP5')
globalMap.set('chartsAppOption', '渠道 APP 使用 TOP5')
globalMap.set('chartsPushUserOption', '推送用户 TOP5')
