# MQ 类型选择
#mq-type: rabbitmq
#mq-type: rocketmq
#mq-type: redis
mq-type: none

# 缓存是否启用
cache-enable: false

#rocketmq:
#rocketmq:
#  name-server: localhost:9876 # 访问地址
#  producer:
#    group: Pro_Group # 必须指定group
#    send-message-timeout: 10000 # 消息发送超时时长，默认3s
#    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
#    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2

spring:
  #  cache:
  #    type: none 即可关闭缓存功能
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password: a6616270
      database: 0
      timeout: 5s
      lettuce:
        pool:
          max-active: 20
          max-idle: 30
          min-idle: 5
          max-wait: 10s
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/deliver?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # RabbitMQ 配置
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: deliver
#    publisher-confirm-type: correlated

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启 sql 日志
    map-underscore-to-camel-case: true

#禁止 spring-actuator 的 rabbit 健康检测
management:
  health:
    rabbit:
      enabled: false